### ISSUE TITLE
Duplicate information on Items/Blueprints page

### ISSUE THREAD

**Issue by Hyllesen** [Skippeh/calcrust.com-frontend#5]
I think you should remove the left bar and just keep the right bar with cooking ingredients and lvl/xp stats. What is the point of having the left bar?

![image](https://cloud.githubusercontent.com/assets/9279498/17226023/9d68ec32-5507-11e6-88f0-2f21292b99d8.png)

None the less quite interesting project.

**Comment by Skippeh** [comment]
Should probably redesign that page yeah.

The original idea behind was that there'd be one list for all items including the ones that can't be crafted, and a list of all craftable items with their requirements underneath like the game (pre xp system).

It's probably better to have it all in one list, then show requirements if that item can be crafted. Would be a lot friendlier for smaller resolutions as well which is a big plus.

**Comment by Hyllesen** [comment]
You could implement categories
![image](https://cloud.githubusercontent.com/assets/9279498/17237518/0f6f1ebe-5553-11e6-9f76-5a0727eec0df.png)

**Comment by bighuggies** [comment]
Merging into one list with categories would go a long way to improving the performance of the items page. ng-repeat can take a long time to render with a lot of complex items.

**Comment by Hyllesen** [comment]
Yeah perhaps the limit wouldn't be needed.

**Comment by bighuggies** [comment]
I have an implementation of the categorised item list:

http://i.imgur.com/2udI0QG.jpg

I'm just not sure where to get the icons from or if it's even a good idea to use icons (they were always confusing in game).

**Comment by Hyllesen** [comment]
I like the use of text instead of icons bighuggies, but maybe have a "All" section also?

**Comment by Skippeh** [comment]
We could use icons and set the tooltip to their equivalent names. Looks good though aside from the tiny text and no "all" category like @Hyllesen said.

Before when there were blueprint frags etc, i had it so you could hold ctrl to select/deselect multiple categories, and one for toggling all categories. If you're unsure how to code it, my (removed) code can be found here (uncommented though): https://github.com/Skippeh/calcrust.com-frontend/commit/e53697c74c34454cb17bf57d9c70eab1dfda9e39. The inactive style is css (https://github.com/Skippeh/calcrust.com-frontend/blob/master/src/scss/ui.scss#L217)

Here's a video of it (kinda broken though because the images doesn't exist and the api doesn't have the blueprint info anymore so no results)
https://gfycat.com/RegalSeveralFrigatebird

I'm pretty sure i can find the icons, give me a few minutes.

**Comment by Skippeh** [comment]
I pushed the icons.
